// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1ebr8iWpYkxa4bF6IWoNXc4DQlDmWoJs',
    appId: '1:510156006786:web:6155831c99620832995b9b',
    messagingSenderId: '510156006786',
    projectId: 'e-commerse-40160',
    authDomain: 'e-commerse-40160.firebaseapp.com',
    storageBucket: 'e-commerse-40160.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7dO0nGMma2U1ZuePCpW1SETC-bZ36vUQ',
    appId: '1:510156006786:android:57c478e8c416b31f995b9b',
    messagingSenderId: '510156006786',
    projectId: 'e-commerse-40160',
    storageBucket: 'e-commerse-40160.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6hRIQ_jvVfx-FkjyWzVLEeRiUg5J3ofM',
    appId: '1:510156006786:ios:e85403e39deb225a995b9b',
    messagingSenderId: '510156006786',
    projectId: 'e-commerse-40160',
    storageBucket: 'e-commerse-40160.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6hRIQ_jvVfx-FkjyWzVLEeRiUg5J3ofM',
    appId: '1:510156006786:ios:689201e05fc0583f995b9b',
    messagingSenderId: '510156006786',
    projectId: 'e-commerse-40160',
    storageBucket: 'e-commerse-40160.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
